version: "3.1"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=takehome
      - POSTGRES_PASSWORD=takehome
    volumes:
      - takehome-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  takehome-pgdata:
